### ISSUE TITLE
Items_XX 파일 형식 유지 여부, 잡지 이름 번역 스타일(의역/직역) 관련

### ISSUE THREAD

**Issue by Drteray** [Aoyamablue/-#4]
1. Items_XX 파일 형식 유지 여부
지금 거의 대부분 아이템 이름이 들어가는 파일명으로 Items_XX를 사용 중이고 일부 Items와 ItemName을 혼용하고 있습니다. 문구 출력에는 지장이 없는 것 같긴 하지만, 공식적으로 Items가 버려지고 ItemName으로의 변경이 권장되고 있어, 통일성의 측면에서도 ItemName으로 맞추는 것은 어떤가요?
(만약 바꾸게 된다면 시간이 많이 걸릴 것 같아서 번역 작업이 전부 끝난 뒤 검수 과정에서 변환하는 식으로 진행되어야 할 것 같습니다)

2. 잡지 이름 번역 스타일
SkillsMag 모드에 있는 잡지 이름이 다수 의역되어 있는데(예: 'Axe Combat' Magazine -> 잡지 '바이킹의 잔인함을 상징하는 무기!'), 이 잡지 이름 번역 부분은 의역하기로 합의가 이루어졌었을까요? 플레이나 이해에 큰 영향은 없어 그대로 두어도 상관은 없을 것 같지만 그래도 혹시 몰라 여쭤봅니다.

**Comment by Aoyamablue** [comment]
1. 변환 할 생각은 있지만, 시간이 많이 걸릴거 같아서 문구출력에 문제가 생기면 그 때 하는 것이 좋을 거 같습니다.
   누락된 부분의 경우는 말씀대로 Itemname기반으로 추가하고 있습니다.

3.[Bandperry]님이 우선 번역하신 부분이라 의견로 여쭤봐야 할 거 같습니다.

**Comment by Drteray** [comment]
1. 그럼 현재 상태로 두겠습니다.

2. 네, 적어두는 걸 깜빡했는데, SkillsMag 검수는 이 이슈 해결까지 잠깐 보류하겠습니다.

@Bandperry

**Comment by Bandperry** [comment]
1. 저 뿐만 아니라 다른 분들의 시간도 소중하므로, 매우 필수적인 경우가 아니라면 그대로 둬도 어떨까 생각합니다. 연말시즌인만큼 여유시간이 없는 경우 누군가 더 작업량에 부담을 질테고 그에 대해 미안함도 느끼기 때문에 작업량이 더 늘어나는 것을 바라지는 않습니다만, 찬성하시는 분들이 많으시다면 저도 신경써서 도울 수 있도록 하겠습니다.

2. 모드를 개인용으로 번역하고 사용하려는 목적에서 단순 직역은 딱딱하고 재미없다고 여겼기 때문에 각색을 주어 의역을 하였습니다. 툴팁에 정확한 목적이 기재되어있으므로 문제는 없다고 생각하고 오히려 파밍하는 플레이어 입장에서 '이건 뭐지' 하고 흥미를 더 가지지 않을까 합니다. 하지만 어디까지나 순수 제 생각이고 제가 혼자 쓰던 경우에서 이제는 통합본으로 넘어왔으므로 다른 분들의 의견을 존중하여 지나친 의역이라고 염려를 표하신다면 의역 없이 재수정하는 것에 따르겠습니다.

**Comment by Drteray** [comment]
2. 툴팁에 무슨 기술 잡지인지 표시된다는 걸 생각하지 못했네요. 이 부분은 그냥 스타일 문제라 이견이 없는 경우 Bandperry님 번역을 유지하는 것이 괜찮을 것 같습니다.
(+ 다만, 물건관리 잡지인 '물건을 쌓는 법!(Maintenance)'의 경우 기술에 맞게 바꾸면 좋을 것 같습니다. 물건 아껴 쓰는 법이라든지...)

**Comment by Aoyamablue** [comment]
2. 모든 의견에 동의합니다.Maintenance는 유지보수나 물건관리가 의미가 정확해서 변경하는것이 좋아보입니다.

**Comment by Drteray** [comment]
정리하고 이슈 닫도록 하겠습니다.
1. 추후 문제 발생 시 ItemName으로 변경하며, 누락된 아이템 이름은 ItemName으로 끌어오기
2. 현재 번역 유지
